[package]
name = "taskgroup_manager"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.12.0", features = ["rt-multi-thread", "macros"] }
task-group = "0.2.1"
futures = "0.3.17"

[target.'cfg(unix)'.dependencies]
nix = "0.23.0"
